<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Filter [
<!ELEMENT Filter  (Type, Parameters*, Description,Condition*)> 
<!ELEMENT Type (#PCDATA)>
<!ELEMENT Parameters (Key,Value)>
<!ELEMENT Key  (#PCDATA)>
<!ELEMENT Value (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Condition   (LHS,OP,RHS)>
<!ELEMENT LHS (#PCDATA)>
<!ELEMENT OP  (#PCDATA)>
<!ELEMENT RHS (#PCDATA)>
]>

<Filter>
<Type><![CDATA[CACHE]]></Type>
<Description><![CDATA[]]></Description>
<Condition>
<LHS><![CDATA[STMT_TOKEN]]></LHS>
<OP><![CDATA[<&gt;]]></OP>
<RHS><![CDATA[OQT]]></RHS>
</Condition>
</Filter>