<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE filter [
<!ELEMENT filter (element*)> 

<!ELEMENT	element	(colname,datatype,comment)>
  <!ELEMENT	colname		(#PCDATA)>
  <!ELEMENT	datatype	(#PCDATA)>
  <!ELEMENT	comment		(#PCDATA)>
]>

<filter>

<element>
  <colname> <![CDATA[QUERYNO]]></colname>
  <datatype>  <![CDATA[INT_DATA]]></datatype>
  <comment> <![CDATA[01020600]]></comment>
</element>
<element>
  <colname> <![CDATA[FUNCTION_NAME]]></colname>
  <datatype>  <![CDATA[CHAR_DATA]]></datatype>
  <comment> <![CDATA[01020601]]></comment>
</element>
<element>
  <colname> <![CDATA[SCHEMA_NAME]]></colname>
  <datatype>  <![CDATA[CHAR_DATA]]></datatype>
  <comment> <![CDATA[01020602]]></comment>
</element>
<element>
  <colname> <![CDATA[APPLNAME]]></colname>
  <datatype>  <![CDATA[CHAR_DATA]]></datatype>
  <comment> <![CDATA[01020603]]></comment>
</element>
<element>
  <colname> <![CDATA[PROGNAME]]></colname>
  <datatype>  <![CDATA[CHAR_DATA]]></datatype>
  <comment> <![CDATA[01020604]]></comment>
</element>
<element>
  <colname> <![CDATA[COLLID]]></colname>
  <datatype>  <![CDATA[CHAR_DATA]]></datatype>
  <comment> <![CDATA[01020605]]></comment>
</element>
<element>
  <colname> <![CDATA[EXPLAIN_TIME]]></colname>
  <datatype>  <![CDATA[TIMESTAMP]]></datatype>
  <comment> <![CDATA[01020606]]></comment>
</element>
</filter>
